import {
  ActionReducer,
  ActionReducerMap,
  createFeatureSelector,
  createSelector,
  MetaReducer
} from '@ngrx/store';
import { environment } from '../../environments/environment';

export interface TypeTest {
  message: 'This is a autogenerated message';
  userMessage: '';
}


export interface State {
  typetest: TypeTest;
}

export const reducers: ActionReducerMap<State> = {

  // typetest:


};


export const metaReducers: MetaReducer<State>[] = !environment.production ? [] : [];
